version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:2022.07.1
    parallelism: 5
    steps:
      - checkout
      - run:
          command: |
            while true; do
              sleep 1
              ps auxwwf
              echo "======"
            done
